spring.application.name=dns-api
server.address=0.0.0.0
server.port=${SERVER_PORT:8080}

dns.upstream.host=${DNS_UPSTREAM_HOST:8.8.8.8}
dns.upstream.port=${DNS_UPSTREAM_PORT:53}
dns.upstream.timeout-ms=${DNS_UPSTREAM_TIMEOUT_MS:5000}
