apiVersion: v1
kind: Service
metadata:
  name: dns-interceptor
spec:
  type: {{ .Values.interceptor.service.type }}
  selector:
    app: dns-interceptor
  ports:
    - name: dns
      port: {{ .Values.interceptor.service.port }}
      targetPort: {{ .Values.interceptor.port }}
      protocol: UDP
