apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-ui
  template:
    metadata:
      labels:
        app: dns-ui
    spec:
      containers:
        - name: dns-ui
          image: "{{ .Values.ui.image }}:{{ .Values.ui.tag }}"
          imagePullPolicy: {{ .Values.ui.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.port }}
              protocol: TCP
