apiVersion: v1
kind: Service
metadata:
  name: dns-ui
spec:
  type: NodePort
  selector:
    app: dns-ui
  ports:
    - name: http
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
      nodePort: {{ .Values.ui.nodePort }}
      protocol: TCP
