create table if not exists dns_records (
    id bigint generated by default as identity primary key,
    domain text not null unique,
    policy text not null check (policy in ('single', 'multi', 'weight', 'geo')),
    ttl integer not null check (ttl > 0)
);

create table if not exists dns_addresses (
    id bigint generated by default as identity primary key,
    record_id bigint not null references dns_records(id) on delete cascade,
    address inet not null check (family(address) = 4 and masklen(address) = 32),
    weight integer not null default 1 check (weight > 0),
    country char(2),
    unique (record_id, address)
);

create table if not exists ip_country_networks (
    id bigint generated by default as identity primary key,
    network cidr not null unique,
    country char(2) not null
);
